<template>
  <div class="app-shell">
    <header class="site-header">
      <div class="header-inner">
        <a class="brand" href="#top" aria-label="NimbusPact home">
          <span class="brand-mark"><CloudRain :size="18" stroke-width="2.2" /></span>
          <span>NimbusPact</span>
        </a>
        <nav class="nav-links" aria-label="Main navigation">
          <a href="#top">Overview</a>
          <a href="#coverage">My covers</a>
          <a href="#how-it-works">How it works</a>
          <a href="#trust">Trust model</a>
        </nav>
        <div class="header-actions">
          <span class="network-pill"><span class="status-dot"></span>{{ networkDisplay }}</span>
          <button class="wallet-button" :class="{ connected: walletAddress }" @click="handleWallet">
            <WalletCards :size="15" /><span>{{ walletAddress ? shortAddress(walletAddress) : "Connect wallet" }}</span>
          </button>
        </div>
      </div>
    </header>

    <main id="top">
      <section class="hero-shell section-width">
        <div class="hero-copy">
          <span class="eyebrow eyebrow-light">Weather cover, settled by consensus</span>
          <h1>Cover the weather.<br /><em>Trust the trail.</em></h1>
          <p class="hero-lede">Choose a condition, fund an exact payout, and let public weather evidence settle the cover through GenLayer consensus.</p>
          <div class="hero-actions">
            <button class="button button-primary" @click="openCreateFlow">Create cover <ArrowRight :size="16" /></button>
            <a class="button button-quiet-light" href="#how-it-works">How settlement works <ArrowDownRight :size="15" /></a>
          </div>
          <div class="hero-footnote"><ShieldCheck :size="14" /> Exact escrow. No project-operated oracle.</div>
        </div>
        <aside class="hero-proof" aria-label="NimbusPact V2 live proof">
          <div class="proof-topline"><span class="proof-label">V2 live proof</span><span class="proof-chip"><CircleCheck :size="12" /> Finalized</span></div>
          <div class="proof-amount">0.01 <span>GEN escrow</span></div>
          <p class="proof-copy">A real browser-funded cover on GenLayer Bradbury, reconciled from the original transaction hash.</p>
          <div class="proof-state"><span class="state-icon"><CircleCheck :size="15" /></span><span><strong>Cover funded</strong><small>Policy p-1 · ACTIVE</small></span></div>
          <dl class="proof-meta"><div><dt>Consensus</dt><dd>5 / 5 AGREE</dd></div><div><dt>Execution</dt><dd>FINISHED_WITH_RETURN</dd></div><div><dt>Escrow</dt><dd>Exact payout value</dd></div></dl>
          <details class="proof-details"><summary>View developer proof</summary><code>0xef9d035c4d...6c2e3c56</code><code>0x055F97140CE35FD1e656ebb3D204952A46646681</code></details>
        </aside>
      </section>

      <section class="credibility-rail section-width" aria-label="NimbusPact product principles">
        <div><span class="rail-number">01</span><strong>Public evidence</strong><p>One fixed Open-Meteo Archive request, constructed from the cover terms.</p></div>
        <div><span class="rail-number">02</span><strong>Consensus verified</strong><p>Validators independently inspect the same evidence before settlement.</p></div>
        <div><span class="rail-number">03</span><strong>Exact escrow</strong><p>The payout you set is the value the contract holds. Network fees stay separate.</p></div>
        <div><span class="rail-number">04</span><strong>Refund path</strong><p>Not triggered or safely unavailable? The creator has a defined recovery path.</p></div>
      </section>

      <section id="coverage" class="dashboard section-width">
        <div class="section-intro dashboard-intro">
          <div><span class="section-kicker">Your coverage desk</span><h2>Weather cover,<br /><em>kept in view.</em></h2></div>
          <div class="dashboard-intro-side"><p>Track funded covers, observation windows, and finalized settlement from one calm workspace.</p><button class="button button-dark" @click="openCreateFlow">New cover <ArrowRight :size="15" /></button></div>
        </div>

        <div v-if="notice" class="notice" :class="`notice-${notice.kind}`" role="status">
          <component :is="notice.kind === 'success' ? CircleCheck : notice.kind === 'warning' ? Clock3 : AlertTriangle" :size="17" />
          <div class="notice-copy"><strong>{{ notice.kind === "warning" ? "Transaction update" : notice.kind === "success" ? "Done" : "Action needed" }}</strong><span>{{ notice.message }}</span></div>
          <details v-if="notice.diagnostic" class="technical-details notice-diagnostic"><summary>Technical details</summary><code>{{ notice.diagnostic }}</code></details>
          <button class="icon-button" aria-label="Dismiss message" @click="notice = null">&times;</button>
        </div>

        <section v-if="transaction.phase !== 'idle'" class="transaction-card" :class="`transaction-${transaction.phase}`" aria-live="polite">
          <div class="transaction-heading"><div class="transaction-heading-copy"><span class="section-kicker">{{ transaction.label }}</span><h3>{{ transactionHeadline }}</h3><p>{{ transactionMessage }}</p></div><div class="transaction-elapsed" v-if="transaction.startedAt"><span>Elapsed</span><strong>{{ elapsedLabel }}</strong></div></div>
          <ol class="transaction-timeline" aria-label="GenLayer transaction lifecycle">
            <li v-for="(step, index) in transactionSteps" :key="step" :class="{ complete: index < transactionStage, current: index === transactionStage && transaction.phase !== 'success' && transaction.phase !== 'failure', failed: transaction.phase === 'failure' && index === transactionStage }"><span class="timeline-marker"><CircleCheck v-if="index < transactionStage || transaction.phase === 'success'" :size="13" /><span v-else>{{ index + 1 }}</span></span><span><strong>{{ step }}</strong><small v-if="index === transactionStage && transaction.phase !== 'success' && transaction.phase !== 'failure'">{{ transaction.phase === "pending" ? "Still in progress" : "Current step" }}</small></span></li>
          </ol>
          <div class="transaction-footer"><div class="hash-block"><span>Transaction hash</span><code v-if="transaction.hash">{{ transaction.hash }}</code><span v-else>Waiting for wallet response</span></div><div class="transaction-actions"><button v-if="transaction.hash" class="button button-outline" :disabled="loading" @click="refresh"><RefreshCw :class="{ spinning: loading }" :size="14" /> Check status</button><button class="text-button" @click="transaction.phase === 'pending' ? null : dismissTransaction()">{{ transaction.phase === "pending" ? "Leave this page safely" : "Dismiss" }}</button></div></div>
        </section>

        <div v-if="recovery.length" class="recovery-card">
          <span class="recovery-icon"><Clock3 :size="17" /></span><div class="recovery-copy"><span class="section-kicker">Transaction recovery</span><h3 v-if="recovery[0]?.hash">Tracking the original transaction</h3><h3 v-else>Review the previous request</h3><p v-if="recovery[0]?.hash">NimbusPact will reconcile the saved hash and will never submit a duplicate automatically.</p><p v-else>No transaction ID was returned. Confirm the wallet did not approve a request before releasing this local retry lock.</p></div><button v-if="recovery[0]?.hash" class="button button-outline" :disabled="loading" @click="refresh"><RefreshCw :size="14" /> Check status</button><button v-else class="button button-outline" :disabled="loading" @click="releaseRecovery(recovery[0])">Release retry lock</button>
        </div>

        <div class="coverage-toolbar"><div class="filter-tabs" role="tablist" aria-label="Filter covers"><button v-for="filter in coverageFilters" :key="filter.key" role="tab" :aria-selected="dashboardFilter === filter.key" :class="{ active: dashboardFilter === filter.key }" @click="dashboardFilter = filter.key">{{ filter.label }} <span>{{ filter.count }}</span></button></div><button class="text-button" :disabled="loading" @click="refresh"><RefreshCw :class="{ spinning: loading }" :size="14" /> {{ loading ? "Refreshing" : "Refresh state" }}</button></div>

        <div v-if="!policies.length && !loading" class="empty-state"><span class="empty-icon"><CloudSun :size="26" /></span><span class="section-kicker">A clear start</span><h3>No covers yet</h3><p>Choose a weather condition and fund your first exact-payout cover.</p><button class="button button-dark" @click="openCreateFlow">Create cover <ArrowRight :size="15" /></button></div>
        <div v-else-if="!filteredPolicies.length" class="empty-filter-state"><p>No covers match this view.</p><button class="text-button" @click="dashboardFilter = 'all'">Show all covers</button></div>
        <div v-else class="policy-grid">
          <article v-for="policy in filteredPolicies" :key="policy.policy_id" class="policy-card" :class="{ selected: selectedPolicy?.policy_id === policy.policy_id }" tabindex="0" role="button" @click="selectPolicy(policy)" @keydown.enter="selectPolicy(policy)" @keydown.space.prevent="selectPolicy(policy)">
            <div class="policy-card-top"><span class="policy-id">{{ policy.policy_id }}</span><span class="status-tag" :class="statusClass(policy.status)">{{ statusLabel(policy.status) }}</span></div>
            <div class="policy-card-main"><div><h3>{{ policy.location_name }}</h3><p>{{ triggerLabel(policy.trigger_type) }} <span aria-hidden="true">&middot;</span> {{ dateLabel(policy.start_date) }} - {{ dateLabel(policy.end_date) }}</p></div><strong>{{ formatGen(policy.payout_amount) }} <small>GEN</small></strong></div>
            <div class="policy-rule"><span>{{ metricUnit(policy.metric) }}</span><strong>&ge; {{ policy.threshold }}</strong></div>
            <div class="policy-card-bottom"><span class="policy-beneficiary"><UserRound :size="13" /> {{ shortAddress(policy.beneficiary) }}</span><div class="policy-actions"><button v-if="policy.status === 'ACTIVE'" class="inline-button" :disabled="busy || !resolutionWindowClosed(policy)" :title="resolutionWindowClosed(policy) ? 'Resolve cover' : 'Observation is still in progress'" @click.stop="resolve(policy)"><Radar :size="13" /> {{ resolutionWindowClosed(policy) ? "Resolve" : "Observation in progress" }}</button><button v-else-if="policy.status === 'DATA_UNAVAILABLE' && canRetry(policy)" class="inline-button" :disabled="busy" @click.stop="resolve(policy)"><RefreshCw :size="13" /> Retry verification</button><button v-else-if="policy.status === 'TRIGGERED' && !policy.withdrawn" class="inline-button inline-button-dark" :disabled="busy" @click.stop="claim(policy)"><HandCoins :size="13" /> Claim payout</button><button v-if="canRefund(policy)" class="inline-button inline-button-refund" :disabled="busy" @click.stop="refund(policy)"><HandCoins :size="13" /> Claim refund</button></div></div>
            <p v-if="policy.status === 'ACTIVE'" class="policy-timing">Observation closes {{ formatUtcTimestamp(observationCloseTimestamp(policy)) }}.</p><p v-else-if="policy.status === 'DATA_UNAVAILABLE' && refundAvailableTimestamp(policy)" class="policy-timing">Refund available after {{ formatUtcTimestamp(refundAvailableTimestamp(policy) || 0) }}.</p>
          </article>
        </div>
      </section>

      <section v-if="selectedPolicy" class="detail-panel section-width" aria-live="polite">
        <div class="detail-header"><div><span class="section-kicker">Cover detail</span><h2>{{ selectedPolicy.location_name }} <span class="muted-id">{{ selectedPolicy.policy_id }}</span></h2></div><div class="detail-header-actions"><span class="status-tag" :class="statusClass(selectedPolicy.status)">{{ statusLabel(selectedPolicy.status) }}</span><button class="icon-button" aria-label="Close cover detail" @click="selectedPolicy = null">&times;</button></div></div>
        <div class="detail-layout"><div class="detail-main">
          <section class="detail-surface terms-surface"><div class="surface-heading"><div><span class="section-kicker">Cover terms</span><h3>{{ triggerLabel(selectedPolicy.trigger_type) }} protection</h3></div><span class="detail-amount">{{ formatGen(selectedPolicy.payout_amount) }} <small>GEN</small></span></div><div class="terms-grid"><div><span>Location</span><strong>{{ selectedPolicy.location_name }}</strong><small>{{ selectedPolicy.latitude }}, {{ selectedPolicy.longitude }}</small></div><div><span>Condition</span><strong>{{ triggerLabel(selectedPolicy.trigger_type) }}</strong><small>{{ metricUnit(selectedPolicy.metric) }} threshold</small></div><div><span>Threshold</span><strong>&ge; {{ selectedPolicy.threshold }} {{ metricUnit(selectedPolicy.metric) }}</strong><small>Measured across the window</small></div><div><span>Observation period</span><strong>{{ dateLabel(selectedPolicy.start_date) }} - {{ dateLabel(selectedPolicy.end_date) }}</strong><small>UTC, on-chain enforced</small></div></div></section>
          <section class="detail-surface"><div class="surface-heading"><div><span class="section-kicker">Status timeline</span><h3>From funding to settlement</h3></div></div><ol class="policy-timeline" aria-label="Cover lifecycle"><li v-for="(step, index) in policySteps" :key="step" :class="{ complete: index < policyStageIndex(selectedPolicy), current: index === policyStageIndex(selectedPolicy) && !['CLAIMED', 'REFUNDED'].includes(selectedPolicy.status) }"><span class="timeline-marker"><CircleCheck v-if="index < policyStageIndex(selectedPolicy) || ['CLAIMED', 'REFUNDED'].includes(selectedPolicy.status)" :size="13" /><span v-else>{{ index + 1 }}</span></span><span><strong>{{ step }}</strong><small v-if="index === 1 && selectedPolicy.status === 'ACTIVE'">Closes {{ formatUtcTimestamp(observationCloseTimestamp(selectedPolicy)) }}</small><small v-else-if="index === 2 && selectedPolicy.status === 'DATA_UNAVAILABLE'">Retry available during recovery</small><small v-else-if="index === 3 && selectedPolicy.status === 'TRIGGERED'">Payout ready for beneficiary</small></span></li></ol></section>
          <section class="detail-surface result-surface"><span class="section-kicker">Settlement result</span><h3>{{ resultTitle(selectedPolicy) }}</h3><p>{{ resultDescription(selectedPolicy) }}</p><div v-if="selectedPolicy.observed_value" class="observed-value"><span>Observed value</span><strong>{{ selectedPolicy.observed_value }} {{ metricUnit(selectedPolicy.metric) }}</strong></div></section>
        </div><aside class="detail-side"><div class="escrow-card"><span class="section-kicker">Escrow</span><strong>{{ formatGen(selectedPolicy.payout_amount) }} <small>GEN</small></strong><p>Held by the V2 Intelligent Contract. Network fees are separate from this amount.</p><div class="escrow-lock"><LockKeyhole :size="14" /> Exact payout value</div></div><div class="side-list"><div><span>Beneficiary</span><strong>{{ shortAddress(selectedPolicy.beneficiary) }}</strong></div><div><span>Funding</span><strong>Finalized</strong><small>State reconciled after execution</small></div><div><span>Settlement</span><strong>{{ selectedPolicy.withdrawn ? (selectedPolicy.status === 'REFUNDED' ? 'Refunded' : 'Transferred') : 'Held' }}</strong></div></div></aside></div>
        <details class="technical-details evidence-details"><summary>Evidence and transaction history</summary><div class="evidence-grid"><div><span>Source</span><strong>Open-Meteo Archive</strong><a :href="selectedPolicy.evidence_url" target="_blank" rel="noreferrer">Open fixed evidence URL <ExternalLink :size="13" /></a></div><div><span>Evidence digest</span><code>{{ selectedPolicy.evidence_digest ? `sha256:${selectedPolicy.evidence_digest}` : "Awaiting resolution" }}</code></div><div><span>Resolution code</span><code>{{ selectedPolicy.resolution_code || "Not resolved" }}</code></div><div><span>Transaction history</span><strong>Funding finalized</strong><small>State is read only after successful execution.</small></div></div></details>
      </section>

      <section id="how-it-works" class="how-section section-width"><div class="section-intro compact-intro"><div><span class="section-kicker">How it works</span><h2>A cover with<br /><em>a clear trail.</em></h2></div><p>Simple on the surface. Deterministic where it matters.</p></div><div class="settlement-path"><div class="path-node"><span>01</span><span class="path-icon"><ShieldCheck :size="19" /></span><h3>Choose</h3><p>Set a location, condition, threshold, and observation window.</p></div><div class="path-connector" aria-hidden="true"></div><div class="path-node"><span>02</span><span class="path-icon"><LockKeyhole :size="19" /></span><h3>Fund</h3><p>Send exactly the payout amount into the payable Intelligent Contract.</p></div><div class="path-connector" aria-hidden="true"></div><div class="path-node"><span>03</span><span class="path-icon"><Radar :size="19" /></span><h3>Observe</h3><p>Wait for the complete UTC window to close before resolution.</p></div><div class="path-connector" aria-hidden="true"></div><div class="path-node"><span>04</span><span class="path-icon"><CircleCheck :size="19" /></span><h3>Settle</h3><p>Consensus produces a triggered payout or a safe creator refund path.</p></div></div></section>

      <section id="trust" class="trust-section section-width"><div class="trust-heading"><span class="section-kicker">Trust model</span><h2>The contract decides.<br /><em>The evidence is visible.</em></h2></div><div class="trust-content"><p class="trust-lede">NimbusPact does not run a private oracle backend. The Intelligent Contract holds the cover terms, validators inspect one fixed public request, and finalized consensus controls settlement.</p><div class="architecture" aria-label="NimbusPact settlement architecture"><div><span>User</span><strong>Funds cover</strong></div><ArrowRight :size="17" /><div><span>Intelligent Contract</span><strong>Locks exact escrow</strong></div><ArrowRight :size="17" /><div><span>GenLayer validators</span><strong>Inspect public evidence</strong></div><ArrowRight :size="17" /><div><span>Settlement</span><strong>Pay or refund</strong></div></div><div class="trust-pills"><span><ShieldCheck :size="14" /> No private oracle</span><span><Fingerprint :size="14" /> Evidence commitment</span><span><Check :size="14" /> Finalized settlement</span></div><details class="technical-details developer-proof"><summary>Developer proof and release history</summary><div class="developer-proof-grid"><div><span>Active V2 contract</span><code data-runtime-binding>{{ runtimeConfig.contractAddress || "unconfigured" }}</code><small>{{ runtimeConfig.networkLabel }}</small></div><div><span>V2 browser proof</span><code>0xef9d035c...6c2e3c56</code><small>FINALIZED · FINISHED_WITH_RETURN · 5/5 AGREE</small></div><div><span>Historical V1</span><code>0xEAA6...C934</code><small>Superseded rejected release. Not active.</small></div></div></details></div></section>
    </main>

    <footer class="site-footer"><div class="footer-inner section-width"><div><span class="brand footer-brand"><span class="brand-mark"><CloudRain :size="16" /></span>NimbusPact</span><p>Parametric weather cover with a settlement trail you can trust.</p></div><div class="footer-links"><a href="#coverage">My covers</a><a href="#how-it-works">How it works</a><a href="#trust">Trust model</a></div><div class="footer-meta"><span>GenLayer Bradbury V2</span><span>Exact escrow · finalized only</span></div></div></footer>

    <div v-if="createOpen" class="modal-backdrop" @click.self="closeCreateFlow"><section class="create-modal" role="dialog" aria-modal="true" aria-labelledby="create-title"><div class="modal-header"><div><span class="section-kicker">Create cover</span><h2 id="create-title">Protect a weather window.</h2></div><button class="icon-button" aria-label="Close create cover flow" :disabled="busy" @click="closeCreateFlow">&times;</button></div><div class="flow-progress" aria-label="Create cover steps"><button v-for="step in 3" :key="step" type="button" :class="{ active: createStep === step, complete: createStep > step }" :aria-current="createStep === step ? 'step' : undefined" @click="createStep > step ? createStep = step : null"><span>{{ createStep > step ? '&#10003;' : step }}</span>{{ step === 1 ? 'Condition' : step === 2 ? 'Payout' : 'Review' }}</button></div>
      <form @submit.prevent="createStep === 3 ? submitCreate() : nextCreateStep()">
        <div v-if="createStep === 1" class="flow-step"><div class="flow-step-heading"><span>01</span><div><h3>Set the condition</h3><p>Define what the cover observes and when the window closes.</p></div></div><div class="form-grid"><label class="field field-span"><span>Location</span><input v-model.trim="form.locationName" required maxlength="64" placeholder="e.g. Lagos Island" /></label><label class="field"><span>Latitude</span><input v-model.trim="form.latitude" inputmode="decimal" required placeholder="6.5244" /></label><label class="field"><span>Longitude</span><input v-model.trim="form.longitude" inputmode="decimal" required placeholder="3.3792" /></label><label class="field"><span>Observation start</span><input v-model="form.startDate" type="date" required /></label><label class="field"><span>Observation end</span><input v-model="form.endDate" type="date" required /></label><label class="field"><span>Weather condition</span><select v-model="form.triggerType" @change="syncThreshold"><option value="HEAVY_RAIN">Heavy rain</option><option value="EXTREME_HEAT">Extreme heat</option><option value="SEVERE_STORM">Severe storm</option></select></label><label class="field"><span>Threshold <small>{{ thresholdUnit }}</small></span><input v-model.trim="form.threshold" inputmode="decimal" required /></label></div><div class="flow-callout"><CalendarDays :size="16" /><span>Resolution becomes available only after the complete UTC observation window closes. The contract enforces this timing on-chain.</span></div></div>
        <div v-else-if="createStep === 2" class="flow-step"><div class="flow-step-heading"><span>02</span><div><h3>Choose who receives the payout</h3><p>The beneficiary is fixed in the policy and can claim only after a triggered result.</p></div></div><div class="form-grid"><label class="field field-span"><span>Beneficiary wallet</span><input v-model.trim="form.beneficiary" required placeholder="0x..." /></label><label class="field field-span"><span>Payout amount <small>GEN</small></span><div class="amount-input"><input v-model.trim="form.payout" inputmode="decimal" required placeholder="0.10" /><span>GEN</span></div></label></div><div class="escrow-explainer"><div class="explainer-icon"><LockKeyhole :size="17" /></div><div><strong>Exact escrow, separate network fee</strong><p>{{ form.payout || '0' }} GEN is the policy escrow. The wallet handles any network transaction charge separately; it is never added to the cover payout.</p></div></div><div class="refund-note"><CircleCheck :size="15" /><span>If the threshold is not reached, the creator can claim the exact escrow back. Temporary evidence failure has a bounded retry and delayed refund path.</span></div></div>
        <div v-else class="flow-step"><div class="flow-step-heading"><span>03</span><div><h3>Review and fund</h3><p>Check the terms before your wallet opens. One transaction will fund the cover.</p></div></div><div class="review-card"><div><span>Location</span><strong>{{ form.locationName || 'Not set' }}</strong></div><div><span>Condition</span><strong>{{ triggerLabel(form.triggerType) }} &ge; {{ form.threshold || '0' }} {{ thresholdUnit }}</strong></div><div><span>Observation window</span><strong>{{ form.startDate || 'Not set' }} - {{ form.endDate || 'Not set' }} UTC</strong></div><div><span>Beneficiary</span><strong>{{ shortAddress(form.beneficiary) }}</strong></div><div class="review-total"><span>Policy escrow</span><strong>{{ form.payout || '0' }} GEN</strong></div></div><div class="review-assurance"><ShieldCheck :size="16" /><span>You are signing the exact payable value shown above. NimbusPact saves the transaction hash and reconciles the same transaction through GenLayer finality.</span></div></div>
        <div class="modal-actions"><button v-if="createStep > 1" class="button button-outline" type="button" :disabled="busy" @click="createStep -= 1">Back</button><span v-else></span><button v-if="createStep < 3" class="button button-dark" type="submit">Continue <ArrowRight :size="15" /></button><button v-else class="button button-dark fund-button" type="submit" :disabled="busy || !configured || !walletAddress"><LoaderCircle v-if="busy" class="spinning" :size="16" /><span v-else>Fund cover</span><ArrowRight v-if="!busy" :size="15" /></button></div><p v-if="!configured" class="form-hint warning-copy">{{ runtimeConfig.configurationError }}</p><p v-else-if="!walletAddress" class="modal-wallet-hint">Connect your wallet on {{ networkDisplay }} before funding.</p>
      </form></section></div>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { AlertTriangle, ArrowDownRight, ArrowRight, CalendarDays, Check, CircleCheck, CloudRain, CloudSun, Clock3, ExternalLink, Fingerprint, HandCoins, LoaderCircle, LockKeyhole, Radar, RefreshCw, ShieldCheck, UserRound, WalletCards } from "lucide-vue-next";
import { canRefundPolicy, canRetryResolution, claimPayout, connectWallet, createPolicy, formatUtcTimestamp, getNetworkLabel, getPendingTransactions, getPolicies, getRuntimeConfig, observationCloseTimestamp, recoverPendingTransactions, refundAvailableTimestamp, refundPolicy, releaseHashlessPending, resolvePolicy, type NoticeKind, type Policy, type PolicyInput, type RecoveryMessage } from "./lib/nimbuspact";
import { NetworkFailure, normalizeNetworkError, policyStatusMessage, type LifecycleOutcome } from "./lib/receiptStatus";
import { defaultObservationDates } from "./lib/policyDates";

const runtimeConfig = getRuntimeConfig();
const configured = runtimeConfig.configured;
const networkLabel = getNetworkLabel();
const networkDisplay = runtimeConfig.network === "testnetBradbury" ? "Bradbury" : networkLabel === "Network configuration missing" ? "Network unavailable" : networkLabel;
const walletAddress = ref<string | null>(null);
const policies = ref<Policy[]>([]);
const selectedPolicy = ref<Policy | null>(null);
const loading = ref(false);
const busy = ref(false);
const recovery = ref(getPendingTransactions());
const notice = ref<{ kind: NoticeKind; message: string; diagnostic?: string } | null>(null);
const createOpen = ref(false);
const createStep = ref(1);
const dashboardFilter = ref("all");
const defaultDates = defaultObservationDates();
const form = ref<PolicyInput>({ locationName: "Lagos Island", latitude: "6.5244", longitude: "3.3792", startDate: defaultDates.startDate, endDate: defaultDates.endDate, triggerType: "HEAVY_RAIN", threshold: "50", beneficiary: "", payout: "0.25" });
const transactionSteps = ["Submitted", "Consensus", "Accepted", "Finality window", "Finalized"];
const policySteps = ["Funded", "Observation", "Verification", "Settlement", "Complete"];
type TransactionPhase = "idle" | "preparing" | "submitted" | "pending" | "success" | "failure";
interface TransactionView { phase: TransactionPhase; label: string; hash: string; startedAt: number; message: string; diagnostic?: string }
const transaction = ref<TransactionView>({ phase: "idle", label: "Transaction", hash: "", startedAt: 0, message: "" });
const transactionNow = ref(Date.now());
let transactionTimer: number | undefined;

const thresholdUnit = computed(() => form.value.triggerType === "HEAVY_RAIN" ? "mm" : form.value.triggerType === "EXTREME_HEAT" ? "C" : "km/h");
const lockedCollateral = computed(() => { const total = policies.value.reduce((sum, policy) => policy.withdrawn ? sum : sum + BigInt(policy.payout_amount || "0"), 0n); return `${formatGen(total.toString())} GEN`; });
const coverageFilters = computed(() => [{ key: "all", label: "All covers", count: policies.value.length }, { key: "active", label: "Active", count: policies.value.filter((policy) => policy.status === "ACTIVE").length }, { key: "awaiting", label: "Awaiting settlement", count: policies.value.filter((policy) => ["ACTIVE", "DATA_UNAVAILABLE"].includes(policy.status)).length }, { key: "triggered", label: "Triggered", count: policies.value.filter((policy) => policy.status === "TRIGGERED").length }, { key: "refundable", label: "Refundable", count: policies.value.filter((policy) => canRefund(policy)).length }, { key: "completed", label: "Completed", count: policies.value.filter((policy) => ["CLAIMED", "REFUNDED"].includes(policy.status)).length }]);
const filteredPolicies = computed(() => policies.value.filter((policy) => { if (dashboardFilter.value === "active") return policy.status === "ACTIVE"; if (dashboardFilter.value === "awaiting") return ["ACTIVE", "DATA_UNAVAILABLE"].includes(policy.status); if (dashboardFilter.value === "triggered") return policy.status === "TRIGGERED"; if (dashboardFilter.value === "refundable") return canRefund(policy); if (dashboardFilter.value === "completed") return ["CLAIMED", "REFUNDED"].includes(policy.status); return true; }));
const transactionStage = computed(() => transaction.value.phase === "success" ? 5 : transaction.value.phase === "pending" ? 3 : transaction.value.phase === "submitted" ? 1 : 0);
const transactionHeadline = computed(() => transaction.value.phase === "preparing" ? "Preparing your cover" : transaction.value.phase === "submitted" ? "Transaction submitted" : transaction.value.phase === "pending" ? "Still awaiting finality" : transaction.value.phase === "success" ? "Cover funded successfully" : "Transaction could not be completed");
const transactionMessage = computed(() => transaction.value.phase === "preparing" ? "Your wallet request is being prepared. The policy escrow remains separate from any network fee." : transaction.value.phase === "submitted" ? "Your transaction hash is saved. NimbusPact is following its path through GenLayer consensus." : transaction.value.phase === "pending" ? "GenLayer finality can take some time. You can leave this page safely; NimbusPact will continue reconciling the same transaction and will never submit a duplicate automatically." : transaction.value.phase === "success" ? transaction.value.message : transaction.value.message || "No transaction state was accepted.");
const elapsedLabel = computed(() => { if (!transaction.value.startedAt) return "-"; const seconds = Math.max(0, Math.floor((transactionNow.value - transaction.value.startedAt) / 1000)); if (seconds < 60) return `${seconds}s`; const minutes = Math.floor(seconds / 60); return `${minutes}m${seconds % 60 ? ` ${seconds % 60}s` : ""}`; });

function shortAddress(address: string): string { return address ? `${address.slice(0, 6)}...${address.slice(-4)}` : "Not set"; }
function formatGen(value: string): string { try { const amount = BigInt(value || "0"); const whole = amount / 1000000000000000000n; const fraction = (amount % 1000000000000000000n).toString().padStart(18, "0").slice(0, 4).replace(/0+$/, ""); return fraction ? `${whole}.${fraction}` : whole.toString(); } catch { return "0"; } }
function dateLabel(value: string): string { const date = new Date(`${value}T00:00:00Z`); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" }); }
function triggerLabel(trigger: string): string { return trigger === "HEAVY_RAIN" ? "Heavy rain" : trigger === "EXTREME_HEAT" ? "Extreme heat" : "Severe storm"; }
function metricUnit(metric: string): string { return metric === "PRECIPITATION_MM" ? "mm" : metric === "TEMPERATURE_MAX_C" ? "C" : "km/h"; }
function statusLabel(status: string): string { return status === "ACTIVE" ? "Active" : status === "TRIGGERED" ? "Triggered" : status === "NOT_TRIGGERED" ? "Not triggered" : status === "DATA_UNAVAILABLE" ? "Evidence unavailable" : status === "REFUNDED" ? "Refunded" : "Claimed"; }
function statusClass(status: string): string { return `status-${status.toLowerCase()}`; }
function resultTitle(policy: Policy): string { return policy.status === "TRIGGERED" || policy.status === "CLAIMED" ? "Weather trigger confirmed" : policy.status === "NOT_TRIGGERED" ? "Threshold not reached" : policy.status === "DATA_UNAVAILABLE" ? "Evidence unavailable" : policy.status === "REFUNDED" ? "Escrow refunded" : "Observation in progress"; }
function resultDescription(policy: Policy): string { return policyStatusMessage(policy.status); }
function showNotice(kind: NoticeKind, message: string, diagnostic?: string): void { notice.value = { kind, message, diagnostic }; }
function lifecycleOutcome(error: unknown): LifecycleOutcome | null { const outcome = (error as { outcome?: LifecycleOutcome } | null)?.outcome; return outcome && typeof outcome === "object" ? outcome : null; }
function showError(error: unknown, fallback: string): void { const outcome = lifecycleOutcome(error); if (outcome && outcome.hash && ["PENDING", "TIMEOUT", "UNDETERMINED"].includes(outcome.state)) { stopTransactionTracking(); transaction.value = { phase: "pending", label: transaction.value.label, hash: outcome.hash, startedAt: transaction.value.startedAt || Date.now(), message: "Still awaiting finality" }; showNotice("warning", "Still awaiting finality. The original transaction hash is saved and will be reconciled without rebroadcasting."); return; } const normalized = error instanceof NetworkFailure ? { headline: error.message, diagnostic: error.diagnostic } : normalizeNetworkError(error); transaction.value = { phase: "failure", label: transaction.value.label, hash: transaction.value.hash, startedAt: transaction.value.startedAt, message: normalized.headline || fallback, diagnostic: normalized.diagnostic }; showNotice("error", normalized.headline || fallback, normalized.diagnostic); console.error("NimbusPact transaction diagnostic", error); }
function resolutionWindowClosed(policy: Policy): boolean { return Math.floor(Date.now() / 1000) >= observationCloseTimestamp(policy); }
function canRetry(policy: Policy): boolean { return canRetryResolution(policy); }
function canRefund(policy: Policy): boolean { return Boolean(walletAddress.value) && canRefundPolicy(policy, walletAddress.value || ""); }
function policyStageIndex(policy: Policy): number { if (["CLAIMED", "REFUNDED"].includes(policy.status)) return 5; if (["TRIGGERED", "NOT_TRIGGERED"].includes(policy.status)) return 4; if (policy.status === "DATA_UNAVAILABLE") return 2; return 1; }
function startTransactionTracking(label: string): void { stopTransactionTracking(); const startedAt = Date.now(); transaction.value = { phase: "preparing", label, hash: "", startedAt, message: "" }; transactionTimer = window.setInterval(() => { transactionNow.value = Date.now(); syncPendingHash(startedAt); }, 500); syncPendingHash(startedAt); }
function syncPendingHash(startedAt: number): void { const pending = getPendingTransactions().find((entry) => Boolean(entry.hash) && entry.createdAt >= startedAt - 2000); if (!pending || ["pending", "success", "failure"].includes(transaction.value.phase)) return; transaction.value = { ...transaction.value, phase: "submitted", hash: pending.hash, message: "" }; }
function stopTransactionTracking(): void { if (transactionTimer !== undefined) window.clearInterval(transactionTimer); transactionTimer = undefined; transactionNow.value = Date.now(); }
function dismissTransaction(): void { if (transaction.value.phase !== "pending") transaction.value = { phase: "idle", label: "Transaction", hash: "", startedAt: 0, message: "" }; }
function openCreateFlow(): void { createStep.value = 1; createOpen.value = true; }
function closeCreateFlow(): void { if (!busy.value) createOpen.value = false; }
function nextCreateStep(): void { if (createStep.value === 1 && form.value.startDate > form.value.endDate) { showNotice("error", "Choose an observation end date on or after the start date."); return; } if (createStep.value === 1 && !form.value.locationName) { showNotice("error", "Add a location before continuing."); return; } if (createStep.value === 2 && !form.value.beneficiary) { showNotice("error", "Add a beneficiary wallet before continuing."); return; } createStep.value += 1; }
function syncThreshold(): void { form.value.threshold = form.value.triggerType === "HEAVY_RAIN" ? "50" : form.value.triggerType === "EXTREME_HEAT" ? "35" : "80"; }
function selectPolicy(policy: Policy): void { selectedPolicy.value = policy; }
async function releaseRecovery(entry: { actionKey: string } | undefined): Promise<void> { if (!entry) return; try { const result: RecoveryMessage = await releaseHashlessPending(entry.actionKey); showNotice(result.kind, result.message, result.diagnostic); recovery.value = getPendingTransactions(); } catch (error) { showError(error, "The retry lock could not be released."); } }
async function handleWallet(): Promise<void> { if (walletAddress.value) return; try { walletAddress.value = await connectWallet(); if (!form.value.beneficiary) form.value.beneficiary = walletAddress.value; showNotice("success", `Wallet connected on ${networkDisplay}.`); } catch (error) { showError(error, "Wallet connection was not completed."); } }
async function refresh(): Promise<void> { if (!configured) return; loading.value = true; try { const pendingBefore = getPendingTransactions().find((entry) => Boolean(entry.hash)); const recovered = await recoverPendingTransactions(); recovery.value = getPendingTransactions(); if (recovered.length) { showNotice(recovered[0].kind, recovered[0].kind === "warning" ? "Still awaiting finality. The original transaction remains saved for reconciliation." : recovered[0].message, recovered[0].diagnostic); if (pendingBefore?.hash && recovered[0].kind === "success") transaction.value = { phase: "success", label: pendingBefore.label, hash: pendingBefore.hash, startedAt: pendingBefore.createdAt, message: "The saved transaction finalized successfully." }; } policies.value = await getPolicies(); if (selectedPolicy.value) selectedPolicy.value = policies.value.find((policy) => policy.policy_id === selectedPolicy.value?.policy_id) ?? null; } catch (error) { showError(error, "Could not read NimbusPact state."); } finally { loading.value = false; } }
async function submitCreate(): Promise<void> { if (!walletAddress.value) { showNotice("error", "Connect your wallet before funding a cover."); return; } busy.value = true; startTransactionTracking("Cover funding"); try { const input = { ...form.value, beneficiary: form.value.beneficiary || walletAddress.value }; const policy = await createPolicy(input, walletAddress.value); policies.value = await getPolicies(); selectedPolicy.value = policy; transaction.value = { ...transaction.value, phase: "success", message: `${policy.policy_id} is funded. Escrow was exactly ${form.value.payout} GEN; the network fee was separate.` }; showNotice("success", `${policy.policy_id} is funded. Your cover is now in its observation window.`); createOpen.value = false; } catch (error) { showError(error, "The cover transaction did not complete."); } finally { busy.value = false; stopTransactionTracking(); recovery.value = getPendingTransactions(); } }
async function resolve(policy: Policy): Promise<void> { if (!canRetry(policy)) { const availableAt = policy.status === "DATA_UNAVAILABLE" && refundAvailableTimestamp(policy) ? ` Retry is closed after ${formatUtcTimestamp(refundAvailableTimestamp(policy) || 0)}.` : ` Resolution becomes available after ${formatUtcTimestamp(observationCloseTimestamp(policy))}.`; showNotice("warning", availableAt); return; } busy.value = true; startTransactionTracking(`${policy.policy_id} verification`); try { const result = await resolvePolicy(policy.policy_id, walletAddress.value || ""); policies.value = await getPolicies(); selectedPolicy.value = result; transaction.value = { ...transaction.value, phase: "success", message: "Verification finalized and the cover state was reconciled." }; showNotice(result.status === "TRIGGERED" ? "success" : result.status === "DATA_UNAVAILABLE" ? "warning" : "success", result.status === "TRIGGERED" ? "The weather trigger was confirmed. The payout is ready for the beneficiary." : result.status === "DATA_UNAVAILABLE" ? "Weather evidence could not be verified. Your payout remains protected and retry is available." : "The threshold was not reached. Creator refund is available."); } catch (error) { showError(error, "Verification did not complete."); } finally { busy.value = false; stopTransactionTracking(); recovery.value = getPendingTransactions(); } }
async function claim(policy: Policy): Promise<void> { busy.value = true; startTransactionTracking(`${policy.policy_id} payout`); try { const result = await claimPayout(policy.policy_id, walletAddress.value || ""); policies.value = await getPolicies(); selectedPolicy.value = result; transaction.value = { ...transaction.value, phase: "success", message: "The payout transfer finalized successfully." }; showNotice("success", "Payout claimed. The finalized contract emitted the funded GEN transfer."); } catch (error) { showError(error, "Payout claim did not complete."); } finally { busy.value = false; stopTransactionTracking(); recovery.value = getPendingTransactions(); } }
async function refund(policy: Policy): Promise<void> { busy.value = true; startTransactionTracking(`${policy.policy_id} refund`); try { const result = await refundPolicy(policy.policy_id, walletAddress.value || ""); policies.value = await getPolicies(); selectedPolicy.value = result; transaction.value = { ...transaction.value, phase: "success", message: "The exact escrow returned to the stored policy creator." }; showNotice("success", "Creator refund finalized. The exact escrow returned safely."); } catch (error) { showError(error, "Creator refund did not complete."); } finally { busy.value = false; stopTransactionTracking(); recovery.value = getPendingTransactions(); } }
function onAccountsChanged(accounts: unknown): void { const first = Array.isArray(accounts) ? accounts[0] : null; walletAddress.value = typeof first === "string" ? first : null; if (walletAddress.value && !form.value.beneficiary) form.value.beneficiary = walletAddress.value; }
onMounted(async () => { await refresh(); window.ethereum?.on?.("accountsChanged", onAccountsChanged); });
onBeforeUnmount(() => { stopTransactionTracking(); window.ethereum?.removeListener?.("accountsChanged", onAccountsChanged); });
</script>
